### ISSUE TITLE
mrz-example - windows

### ISSUE THREAD

**Issue by ManoLazar** [DoubangoTelecom/ultimateMRZ-SDK#1]
1. download preview/c++ - compiled correclty in vs2017 - debug / x64
2. on run got error :
Unhandled exception at 0x00007FFB3F9CA839 in mrz_sample.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x00000068828FEF40. occurredUnhandled exception at 0x00007FFB3F9CA839 in mrz_sample.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x00000068828FEF40. occurred

any idea ?

**Comment by DoubangoTelecom** [comment]
Discussion thread:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/doubango-ai/zP-tqSU6YQQ/W-K_hLMiBAAJ

**Comment by DoubangoTelecom** [comment]
Fixed by release 2.0.0
