### ISSUE TITLE
Running the SDK on Web Server

### ISSUE THREAD

**Issue by imranbaloch** [DoubangoTelecom/ultimateMRZ-SDK#23]
Just need to confirm the sample code in your repo will be enough to handle the normal sever load (at least 100 Requests per Minute) or there are some threading issues we need to tackle,

```
            UltMrzSdkResult result = CheckResult("Init", UltMrzSdkEngine.init(BuildJSON(@"SomePathOnWebServer", "")));
            Bitmap image = new Bitmap(somPostedFileToWebServer);
            BitmapData imageData = image.LockBits(new Rectangle(0, 0, image.Width, image.Height), ImageLockMode.ReadWrite, PixelFormat.Format24bppRgb);
            try
            {
                result = CheckResult("Process", UltMrzSdkEngine.process(
                        ULTMRZ_SDK_IMAGE_TYPE.ULTMRZ_SDK_IMAGE_TYPE_RGB24, 
                        imageData.Scan0,
                        (uint)image.Width,
                        (uint)image.Height
                    ));
                 //result.json() include final
            }
            finally
            {
                image.UnlockBits(imageData);
            }
```

There will be a lot of threads that will be executing the same code parallelly. off course, `somPostedFileToWebServer` will be different for each request.

**Comment by DoubangoTelecom** [comment]
Call the `Init` function once at server startup.
You have to protect the process function to avoid concurrent access:
```
mutex.lock();
process();
mutex.unlock();
```
The process function is already massively multithreaded. Without access control you'll be forking the threads and will end up flooding your CPU. On quad core with hyper-threading you'll have 8 threads created by the SDK. If you're using 8 threads to call the process function then, you'll have 8x8=64 threads. Our code is already well designed to avoid context switching and thread forking (https://github.com/DoubangoTelecom/compv/tree/master/base/parallel). See https://www.doubango.org/SDKs/mrz/docs/Architecture_overview.html#thread-safety.

The minimum frame rate is 15fps (https://github.com/DoubangoTelecom/ultimateMRZ-SDK/tree/master/samples/c%2B%2B/benchmark#peformance-numbers) which means you could process at least 900 requests per minutes when all images have MRZ lines.

**Comment by imranbaloch** [comment]
I don't know how 900 RPM will be achieved if you have mutex around the process. Is it the right place to ask a question for support or should we send an email for support(because we already purchased the license)

**Comment by DoubangoTelecom** [comment]
The benchmark application is sequential which means the lock is nop. If you run the benchmark for 1 minute you'll have the maximum requests you can process. 

You can contact our support team at tech at doubango doT org

**Comment by imranbaloch** [comment]
There seems to be an issue running the sample in .NET web application(specifically ASP.NET MVC). When you mark the process(w3wp) as 32 bit it throws TypeInitializationexception but when I mark it as 64 bit it crashes the w3wp process. I checked your console application it marked explicitly application target as x64 but our web application is using AnyCpu. If I change my applications to x64 then my application won't run because of other dependencies.

**Comment by DoubangoTelecom** [comment]
As you can clearly see on the Github pages and the pricing (https://www.doubango.org/pricing.html), we always make sure to write "x86_64" instead of "x86". The binaries distributed are for 64-bit CPUs and we don't have 32-bit version. Because you have a commercial license we'll build a 32-bit version for you but keep in mind many optimizations are not available to these CPUs. If you're planning to build a high performance server it's not a good idea.

**Comment by DoubangoTelecom** [comment]
If you try "AnyCPU" and uncheck "Prefer 32-bit", it woks

**Comment by DoubangoTelecom** [comment]
I have checked on the web and looks like with "AnyCPU" x86_64 binaries will be correctly loaded unless you're running a 32-bit system or have checked "Prefer 32-bit". I'm closing this ticket, if you really want to force your app to run as 32-bit let us know and I'll prepare. Quote from https://stackoverflow.com/questions/516730/what-does-the-visual-studio-any-cpu-target-mean#comment23739204_516743 -> "Which could be terrible if your writing for a server environment and want your application to be able to use more then 2GB of memory. You are also opting out of any x64 JIT optimizations that may someday come down the pipe."

**Comment by imranbaloch** [comment]
Unfortunately, Prefer 32-bit works for executables that run in the process. In web we have a w3wp.exe process. which can be both 32 bit and 64 bit. With 32 bit w3wp.exe process, application throwing an error while in 64-bit w3wp.exe process case it is crashing when calling init,

![image](https://user-images.githubusercontent.com/667961/84196200-f0415180-aab0-11ea-8351-332bd8328dbd.png)

![image](https://user-images.githubusercontent.com/667961/84196480-55954280-aab1-11ea-8a92-9aad3c09a111.png)

**Comment by DoubangoTelecom** [comment]
Sorry but I don't really understand what you're trying to explain. An application cannot be both 32-bit and 64-bit. When you start it the process will be one of 32-bit or 64-bit but not both. Your screen shows **2 different processes**, one is 32-bit and the other is 64-bit. It's normal for the 32-bit to crash but not for the 64-bit. Please share the crash report for the 64-bit process.

**Comment by DoubangoTelecom** [comment]
Also, have you tried to run IIS as 64-bit (https://stackoverflow.com/a/43417170) to check if it crash?

**Comment by DoubangoTelecom** [comment]
https://stackoverflow.com/a/14748308 This one looks more appropriate to enable full x64

**Comment by imranbaloch** [comment]
> Sorry but I don't really understand what you're trying to explain. An application cannot be both 32-bit and 64-bit. When you start it the process will be one of 32-bit or 64-bit but not both. The assembly could embed both architectures but the process is one arch the another.

Actually, I am running my application both in 32 bit and 64 bit that's why you see both applications in above screenshot.

> Also, have you tried to run IIS as 64-bit (https://stackoverflow.com/a/43417170) to check if it crash?

This is for IIS express not IIS (yes IIS and IIS express are different web servers)

> https://stackoverflow.com/a/14748308 This one looks more appropriate to enable full x64

This is what I did for IIS (and thats what you see in screenshot above for running the app in both 32 bit and 64 bit)

I have crash dumps for the application running on 64 bit. Off course you guys can analyse the dump better so please let me know what is the best way to share the dump. At the time of crash there were 60 threads. Exception message was,

`Unhandled exception at 0x00007FFBD3D5E75E (ucrtbase.dll) in MyDump.dmp: Fatal program exit requested.
`
`The assembly instruction at ucrtbase!abort+4e in C:\WINDOWS\System32\ucrtbase.dll has caused an unknown exception (0xc0000409) on thread 51
`

| Function     | Arg 1     | Arg 2     | Arg 3     | Arg 4   | Source | 
|--------------|:---------:|----------:|----------:|--------:|-------:|
| ucrtbase!abort+4e     | 000001e6`00000003     | 00007ffb`00000003     | 00007ffb`3b2a0db0     | 00007ffb`3b2a0df8    | 
| ultimateMRZ_SDK!ultimateMrzSdk::UltMrzSdkResult::operatorAssign+1826d1     | 000001e6`d5c7fc30     | 00000000`00000000     | 00000020`a09cf789     | 00000020`a1e3ab90    | 
| ultimateMRZ_SDK!ultimateMrzSdk::UltMrzSdkResult::operatorAssign+1834c4     | 00000000`00000000     | 000001e6`d5c7fc30     | 00000000`00000000     | 00007ffb`3aead186    | 
| ultimateMRZ_SDK!ultimateMrzSdk::UltMrzSdkResult::operatorAssign+1ba6     | 00000000`00000000     | 00007ffb`3af2f295     | 00000000`00000000     | 00000020`a09cf710    | 
| ultimateMRZ_SDK!ultimateMrzSdk::UltMrzSdkResult::operatorAssign+2fb4     | 000001e6`d341da60     000001e6`d341da60     | 000001e6`d341eb00     | 000001e6`d341da68    | 
| ultimateMRZ_SDK!ultimateMrzSdk::UltMrzSdkResult::operatorAssign+8e629     | 00000000`00000000     | 00000000`00000000     | 00000000`00000000     | 00000000`00000000    | 
| kernel32!BaseThreadInitThunk+14   |   00000000`00000000   |   00000000`00000000     | 00000000`00000000     | 00000000`00000000    | 
| ntdll!RtlUserThreadStart+21     | 00000000`00000000     | 00000000`00000000     | 00000000`00000000     | 00000000`00000000    |

**Comment by DoubangoTelecom** [comment]
I'm not familiar with IIS. Is it possible to retrieve logs to stderr? The assign operator is called before returning a result. Inside this function we call VirtualAlloc. At startup, before reaching this function we print many useful logs (see recognizer sample app). It would be useful for us if we can have these logs. Also, we will probably add more logs to understand the issue.

**Comment by imranbaloch** [comment]
I have ported this in C#. It will be great if can also take a look of this https://gist.github.com/imranbaloch/4c048d1e0bb615cbe784b73f898957fe

**Comment by imranbaloch** [comment]
Also, I think this line should be doc_number instead of doc https://github.com/DoubangoTelecom/ultimateMRZ-SDK/blob/71e507ffc33fb5a24a2fa127c72a41f3755f31e0/samples/c%2B%2B/mrz_parser.h#L256

**Comment by DoubangoTelecom** [comment]
Thanks, I'll review the code

**Comment by imranbaloch** [comment]
Sorry to ask another related question. For finding lines do we need to loop through all zones to find all lines and the first line will be in the first zone?

**Comment by imranbaloch** [comment]
I have a few more questions,

1) I see some fields have with P< and personal number with Should I replace with < with empty? 
2) Do we have a standard of mapping list of countries with code in MRZ?
3) Do we have mapping of P<, VI, C1, etc. document types?

**Comment by DoubangoTelecom** [comment]
> Sorry to ask another related question. For finding lines do we need to loop through all zones to find all lines and the first line will be in the first zone?

A zone defines a group of lines. This means you should have as many zones as documents. If you have 1 document you should have a single zone unless there is a false positive. If you check the sample images at https://www.doubango.org/webapps/mrz/ you'll see that only the 3rd image has 2 zones because there are 2 documents.

So, looping through zones means looping through different documents.

**Comment by DoubangoTelecom** [comment]
> I have a few more questions,
> 
> 1. I see some fields have with P< and personal number with Should I replace with < with empty?
> 2. Do we have a standard of mapping list of countries with code in MRZ?
> 3. Do we have mapping of P<, VI, C1, etc. document types?
> 4. I tried with my id,
> 
> ![image](https://user-images.githubusercontent.com/667961/84564681-83f67480-ad74-11ea-9ca5-f10a149a6029.png)
> 
> ![image](https://user-images.githubusercontent.com/667961/84564689-97094480-ad74-11ea-86d8-e3d347fade39.png)
> 
> In your portal https://www.doubango.org/webapps/mrz/ the surname and given name have issues? Is this is not standard or there might in issue in parsing?

1. Yes, '<' are used to match length. It may also be used as space. Check https://www.doubango.org/SDKs/mrz/docs/MRZ_formats.html
2. Yes, it's defined at https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
3. Yes, see https://www.doubango.org/SDKs/mrz/docs/MRZ_formats.html.
```
switch (Doc) {
	case 'P': document = "Passport"; break;
	case 'V': document = "Visa"; break;
	case 'I': document = "Identity card"; break;
	case 'C': if (firstLineString[1] == '1' && countryCode == "USA") { document = "Permanent resident card"; } break;
	default: break;
	}
```
4. Without seeing the MRZ I don't know. Based on the standard your document should be `QADIR<BAKSH<<IMRAN`

**Comment by imranbaloch** [comment]
Thanks for your detailed answer.

> Without seeing the MRZ I don't know. Based on the standard your document should be QADIR<BAKSH<<IMRAN

Mine is `P<PAKQADIR<BAKSH<<IMRAN<<<<<<<<<<<<<<<<<<<<<` If you see above pic of my passport my surname is `QADIR BAKSH` and given name is `IMRAN`

**Comment by imranbaloch** [comment]
Any idea why expiry date is different here,

![image](https://user-images.githubusercontent.com/667961/84597288-17629f00-ae74-11ea-986f-14c4dba3d62e.png)

**Comment by DoubangoTelecom** [comment]
> Any idea why expiry date is different here,
> 
> ![image](https://user-images.githubusercontent.com/667961/84597288-17629f00-ae74-11ea-986f-14c4dba3d62e.png)

Even without checking you can know the mrz doesn't match the document content (there is no 24). Don't expect specimens to be correct.

**Comment by imranbaloch** [comment]
Thanks. do you have any idea how should we handle YY year case? For example, sometimes we have 30 50 which both means 1950 and 2050

**Comment by DoubangoTelecom** [comment]
> Thanks. do you have any idea how should we handle YY year case? For example, sometimes we have 30 50 which both means 1950 and 2050

Checked but for now I have no idea
