### ISSUE TITLE
Python getting started

### ISSUE THREAD

**Issue by reviloera** [DoubangoTelecom/ultimateMRZ-SDK#27]
How can I use your SDK in my python project. Thank you

**Comment by DoubangoTelecom** [comment]
Unfortunately for now we only support C++, C# and Java.

**Comment by pascal-gujer** [comment]
Guys, please give us an example of how to use your API in python (if money matters: at least 15 raspberry pi licences ahead ;) )

**Comment by DoubangoTelecom** [comment]
Duplicate of #7 

Unfortunately the binaries are not built with Python bindings. We're not planning to update the code for now. We can share the SWIG C++ wrapper with you. You can build it to generate a new library with the Python functions.
