### ISSUE TITLE
GO language starting point

### ISSUE THREAD

**Issue by SoftExpert** [DoubangoTelecom/ultimateMRZ-SDK#38]
Hello,

Is it possible to call the Linux **.so** library methods from GO language?
What would be needed to start with ?

So far I think the following is needed:
`package main

// #cgo LDFLAGS: -L${SRCDIR}/lib -llibultimate_mrz-sdk.so
import "C"
`
but how about the rest (init, deinit and the process methods) ?

Thank you in advance !

Best regards,
SoftExpert

**Comment by DoubangoTelecom** [comment]
Unfortunately we're not familiar with GO. Our shared library has no external dependency, calling it from GO will be the same as any other library. So, your issue is not specific to ultimateMRZ.
