### ISSUE TITLE
Will this work for image rotated to 90 degrees ? Will it suppport rotated images also. Please let me know if there are any custom configurations to be done to support rotated images.

### ISSUE THREAD

**Issue by koko9712** [DoubangoTelecom/ultimateMRZ-SDK#43]

**Comment by DoubangoTelecom** [comment]
If the picture is taken using a smartphone on Portrait mode it'll be 90° rotated ("rotated images") and this information is embedded in the EXIF meta-data. It's up to you to extract this information and provide it to the process function.

Check process function at https://www.doubango.org/SDKs/mrz/docs/cpp-api.html#_CPPv4N14ultimateMrzSdk15UltMrzSdkEngine7processEK21ULTMRZ_SDK_IMAGE_TYPEPKvK6size_tK6size_tK6size_tKi, the last parameter is the EXIF orientation info.

To extract the EXIF orientation info from a JPEG image:

    - Android/Java: https://github.com/DoubangoTelecom/ultimateMRZ-SDK/blob/b43d4896ef1325a76eae2a89026979670895a49a/samples/android/benchmark/src/main/java/org/doubango/ultimateMrz/benchmark/MrzBenchmarkActivity.java#L316

    - C#: https://github.com/DoubangoTelecom/ultimateMRZ-SDK/blob/b43d4896ef1325a76eae2a89026979670895a49a/samples/csharp/recognizer/Program.cs#L220

If for any reason you don't have the EXIF meta-data then, try the picture with "orientation=0" and if no MRZ is found then use "orientation=6" and try again. We don't recommend this hack as there is no reason for an image to be 90° rotated without embedding this information in the meta-data. See https://www.impulseadventure.com/photo/exif-orientation.html

So, to make it clear: If your picture is 90° rotated and there is no meta-data to indicate it then, you're in fault and it's not a limitation. For example, you can try the Android sample and you'll notice that it works when the mobile device is rotated at 90, 180 or 270 degrees thanks to the EXIF meta-data information.

"rotated images" is not a feature or something expected to be supported by our SDK. If you're rotating the document at 90° then, up to you to set the right EXIF orientation or call the process function twice as explained above. Please also note that "rotated images" can be 90° rotated or 270° rotated which means the EXIT orientation value could be 6 or 8 for these images.
