### ISSUE TITLE
Why there are some '*' detected in the result string when running sample?

### ISSUE THREAD

**Issue by abozhang** [DoubangoTelecom/ultimateMRZ-SDK#49]
Like this:
"P<CZ*SP*CIM*N<<VZOR<<<<<<<<<<<<<<<<<<<<<<<<<

is that a detecting error? or just a kind of protection method?

**Comment by DoubangoTelecom** [comment]
Protection method

**Comment by LeoWuYoswit** [comment]
Can i disable it?

**Comment by DoubangoTelecom** [comment]
> Can i disable it?

No

**Comment by DoubangoTelecom** [comment]
> Can i disable it?

No
