### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by waflessnet** [DoubangoTelecom/ultimateMRZ-SDK#5]
Hello, how search licence for linux ?

**Comment by DoubangoTelecom** [comment]
Hello, This repo contains binaries for Android, iOS, Raspberry Pi and Windows. For Linux you'll need a commercial license.

**Comment by DoubangoTelecom** [comment]
Linux binaries have been released in 2.1.0

**Comment by waflessnet** [comment]
OMG.!!  I need the  license linux?
