### ISSUE TITLE
Error "has text relocations"

### ISSUE THREAD

**Issue by nepstor** [DoubangoTelecom/ultimateMRZ-SDK#51]
When I run it, the error

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/****-a2-8BJV7rnDUSflIoVTKcQ==/lib/x86/libultimateMRZ_SDK.so" has text relocations
How can I fix it?

SDK: v28

**Comment by DoubangoTelecom** [comment]
On Android we only support ARM targets
