### ISSUE TITLE
My MRZ project cannot detect tessdata_best 

### ISSUE THREAD

**Issue by Faran-khan000** [DoubangoTelecom/ultimateMRZ-SDK#53]
Hi there, I am badly stuck in the configuration of tessdata_best. Can you tell me how to use tessdata_best in my project? My tesseract OCR engine is getting tessdata by default. And the main thing, how to configure tessdata_best in my source code?

**Comment by DoubangoTelecom** [comment]
This project doesn't use 'tessdata_best', I don't think you're at the right place. You should check Tesseract group.

**Comment by Faran-khan000** [comment]
Can you send me the link to this group if possible? Where can I found this group?
