### ISSUE TITLE
MRZ error

### ISSUE THREAD

**Issue by prontoo** [DoubangoTelecom/ultimateMRZ-SDK#58]
Dear,
 
We have some strange situation. We have implemented your product MRZ reader in Windows service but sometimes we receive some strange errors and code crash, windows service stop work.
 
Below you can find errors from the windows event viewer

-----
Faulting application name: MrzWindowsService.exe, version: 1.0.0.0, time stamp: 0xe6b849ce
Faulting module name: ultimateMRZ-SDK.DLL, version: 2.7.0.0, time stamp: 0x602d2101
Exception code: 0xc0000005
Fault offset: 0x000000000002bde9
Faulting process id: 0x1c34
Faulting application start time: 0x01d794f9a9538a6b
Faulting application path: E:\Apps\MRZservice\Debug\MrzWindowsService.exe
Faulting module path: E:\Apps\MRZservice\Debug\ultimateMRZ-SDK.DLL
Report Id: 8f58fb36-c4fc-4710-acdb-ab497f6b561a
Faulting package full name: 
Faulting package-relative application ID: 
------

------
Faulting application name: MrzWindowsService.exe, version: 1.0.0.0, time stamp: 0xe6b849ce
Faulting module name: ucrtbase.dll, version: 10.0.17763.1490, time stamp: 0x48ac8393
Exception code: 0xc0000409
Fault offset: 0x000000000006e77e
Faulting process id: 0x6d4
Faulting application start time: 0x01d794fa053c6c23
Faulting application path: E:\Apps\MRZservice\Debug\MrzWindowsService.exe
Faulting module path: C:\windows\System32\ucrtbase.dll
Report Id: 9832632d-474f-48ec-89c7-4528e6970db0
Faulting package full name: 
Faulting package-relative application ID: 
------

Can you help us to find the problem?
 
Best regards,
Ivo

**Comment by DoubangoTelecom** [comment]
Please use latest version (2.8) and share full logs if you still have the issue.
