### ISSUE TITLE
New version of MRZ

### ISSUE THREAD

**Issue by prontoo** [DoubangoTelecom/ultimateMRZ-SDK#59]
Hi. I am Goran, software developer at Nextsense, Skopje, Macedonia. 
About 3-4 months we purchased a license for the MRZ SDK which we are using in our system.
However we are encountering a problem about once a month, that the our Windows Service using your dll is restarting without any
obvious reason. You already recommended to my colleague to replace the dll to version 2.8.
Can You please inform us is there any specific procedure that we need to follow or we can simply copy-paste the new dll?
Do we need a new token?

Best Regards, Goran

**Comment by DoubangoTelecom** [comment]
Hi, you need to replace all files. You don't need a new token.

**Comment by DoubangoTelecom** [comment]
Please also note that there is no known issue that restart the service. This is obviously a bug in your side. I recommended using 2.8 because it introduce autolocks to make everything thread-safe. You may be having random concurrent access.
