### ISSUE TITLE
Static UltMrzSdkResult

### ISSUE THREAD

**Issue by nedevskig** [DoubangoTelecom/ultimateMRZ-SDK#61]
Hi. We are using the MRZ Reader (c# API) in a Windows Service.  Is it ok to use a static instance of UltMrzSdkResult like this:
private static UltMrzSdkResult mrzResult;

private string ProcessImage(Bitmap image) 
{
               ...
                // Initialize the engine: Load deep learning models and init GPU shaders
                // This function should be called once.
                // https://www.doubango.org/SDKs/mrz/docs/cpp-api.html#_CPPv4N14ultimateMrzSdk15UltMrzSdkEngine4initEPKc
                if(mrzResult == null)
                {
                    mrzResult = CheckMRZResult("Init", UltMrzSdkEngine.init(...));
                }
              ...
}

**Comment by DoubangoTelecom** [comment]
Yes ... but why?

**Comment by nedevskig** [comment]
So there is no performance or any other issues if we initialize the engine on every call ?  Should we then de-initialize on every call?
