### ISSUE TITLE
Docker runtimeKey : device node not found,  If you try to activate a license, you'll be in big trouble.

### ISSUE THREAD

**Issue by olijouve** [DoubangoTelecom/ultimateMRZ-SDK#65]
Hi,

I've built a docker container and i followed https://github.com/DoubangoTelecom/ultimateMRZ-SDK/blob/master/CONTAINER.md for udev part.

My issue is in the output of  binaries/linux/x86_64/runtimeKey : 

```
runtimeKey --json true --assets ./assets
...
*[COMPV INFO]: [UltMrzSdkEngine] Call: requestRuntimeLicenseKey
*[COMPV INFO]: [UltBaseEngine] UltBaseEngineReadSystemFile: fopen[0] returned null
device node not found
*[COMPV INFO]: [UltBaseEngine] fgets failed, round[0]
device node not found
*[COMPV INFO]: [UltBaseEngine] fgets failed, round[1]
*[COMPV INFO]: [UltBaseEngine] [UltBaseEngineGetXYZ002] fopen, not null
*[COMPV INFO]: [UltBaseEngine] [UltBaseEngineGetXYZ002] No match found
*[COMPV INFO]: [UltBaseEngine] [Activation][S] If you try to activate a license, you'll be in big trouble. On Linux install udev ('apt-get install udev') and try again.
*[ULTMRZ_SDK INFO]: 

{"host_type":"","runtimeKey":"AX+kO_......JDgE="}
```
>> If you try to activate a license, you'll be in big trouble. On Linux install udev ('apt-get install udev') and try again.

udev seems to be ok as this test works in the container:
```
udevadm info /dev/tty0
P: /devices/virtual/tty/tty0
N: tty0
E: DEVNAME=/dev/tty0
E: DEVPATH=/devices/virtual/tty/tty0
E: MAJOR=4
E: MINOR=0
E: SUBSYSTEM=tty
```

We were about to buy a licence but right now we cannot because of this warning.

My Host is a centosOS 7 and the docker is an ubuntu 18.04

**Comment by DoubangoTelecom** [comment]
Hi,

- Run `lsblk` on the host and share the output
- Start the docker container as explained at https://github.com/DoubangoTelecom/ultimateMRZ-SDK/blob/master/CONTAINER.md, run `lsblk` and share the logs

**Comment by olijouve** [comment]
lsblk
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0              11:0    1 1024M  0 rom  
vda             252:0    0   70G  0 disk 
├─vda1          252:1    0    1G  0 part /boot
└─vda2          252:2    0   69G  0 part 
  ├─centos-root 253:0    0 41,7G  0 lvm  /
  ├─centos-swap 253:1    0    7G  0 lvm  [SWAP]
  └─centos-home 253:2    0 20,3G  0 lvm  /home

**Comment by olijouve** [comment]
I've just found out the server that Production IT provides to us is a virtualized one...
Don't have any issue when testing one my own non virtualized system, asking now for non virtualized environnement...

**Comment by DoubangoTelecom** [comment]
> I've just found out the server that Production IT provides to us is a virtualized one... Don't have any issue when testing one my own non virtualized system, asking now for non virtualized environnement...

Yes, this is why we asked to run `lsblk`. `/dev/vda` means it's a virtualized.
