### ISSUE TITLE
Sample can't be run

### ISSUE THREAD

**Issue by AbdulazizRasulbek** [DoubangoTelecom/ultimateMRZ-SDK#67]
When I tried to run android sample some SDK classes are missing like ULTMRZ_SDK_IMAGE_TYPE, UltMrzSdkEngine, UltMrzSdkResult

**Comment by DoubangoTelecom** [comment]
You have to provide more information about what you're trying to do. There is documentation on how to import the project in Android Studio and it's pretty easy.
