### ISSUE TITLE
Parsing of surnames which contain multiple words incorrect

### ISSUE THREAD

**Issue by enricomiletto** [DoubangoTelecom/ultimateMRZ-SDK#70]
Hello,
I think there's an error in the way the names are parsed.
In the screenshot underneath you can see that the name is not parsed correctly.
It should be something like:
```
surname_0 : DE
surname_1: BRUIJN
given_name_0: WILLEKE
given_name_1: LISELOTTE
```
It seems like the parser doesn't allow for surnames that comprise of more than 1 word.
In the MRZ spec both the "Primary Identifier" and the "Secondary Identifier" can contain multiple words, which are in both cases separated by a single `"<"`, while the Primary and Secondary identifiers are are separated from one another by a `"<<"`.

Thanks in advance.
Enrico
![Immagine 2022-03-04 181633](https://user-images.githubusercontent.com/80707578/156810668-9df752ff-2aff-45d0-b748-64d11b3de301.jpg)

**Comment by DoubangoTelecom** [comment]
The SDK doesn't contain a parser, the result is informational. The parser is outside of the SDK and open source (https://github.com/DoubangoTelecom/ultimateMRZ-SDK/tree/master/samples/c%2B%2B/parser), you can modify it.
