### ISSUE TITLE
French driver's license MRZ not recognized

### ISSUE THREAD

**Issue by SoftExpert** [DoubangoTelecom/ultimateMRZ-SDK#76]
Hello,

French driver's license (the credit card sized variant) comes with a single line MRZ.
Currently, it seems the SDK cannot find and process that zone.
Is this a current limitation, is there some additional setting or does the SDK require additional assets/training in order to achieve this ?

Thank you in advance for the response !

Best regards,
SoftExpert

**Comment by SoftExpert** [comment]
Hello,

You dismissed too quickly the issue: I already had set min_num_lines to 1, before opening the case.
Here is my cuurent configuration:
![image](https://user-images.githubusercontent.com/1254018/172669378-f7efff96-6ac9-4bc6-b870-a62859c73361.png)

**Comment by SoftExpert** [comment]
Also, the demo app (https://www.doubango.org/webapps/mrz/) will not recognize it either ...

**Comment by DoubangoTelecom** [comment]
> Also, the demo app (https://www.doubango.org/webapps/mrz/) will not recognize it either ...

The demo is configured min_num_lines equal to 2

**Comment by DoubangoTelecom** [comment]
I got your mail. Please attach the full logs and a sample image to reproduce. The detector should work with single line MRZ is the config is changed.

**Comment by SoftExpert** [comment]
Hello,

As confirmed by email, I identified the issue as being related to the image quality; adjusting the image processing chain on my side, I was able to obtain satisfactory results.
Thank you for the helpful information provided.
