### ISSUE TITLE
Are result sections missing by design in the trial version?

### ISSUE THREAD

**Issue by LjSamardzic** [DoubangoTelecom/ultimateMRZ-SDK#84]
Running the Windows binary for recognizing MRZ, I noticed that the results returned (example below) do not contain sections like "rotation", "orientation", "fields" etc. which are returned by the cloud-based implementation at https://www.doubango.org/webapps/mrz/. Is this one of the security features like the asterisks replacing certain characters or should I set something up differently? 

Also, it would be useful if you added a note in ReadMe saying the asterisks are a security feature since it took me a while to confirm that and I imagine other people may be unsure about it too. 

`"result":{
   "duration":83,
   "frame_id":0,
   "zones":[
      {
         "lines":[
            {
               "confidence":91.0,
               "text":"P<CZ*SP*CIM*N<<VZOR<<<<<<<<<<<<<<<<<<<<<<<<<",
               "warpedBox":[...]
            },
            {
               "confidence":91.0,
               "text":"9900*000<*CZ*1102299F1*090*41152291111<<<<24",
               "warpedBox":[...]
            }
         ],
         "warpedBox":[...]
      }
   ]
}`

**Comment by DoubangoTelecom** [comment]
"rotation" and "orientation" are returned to give feedback to the webapp in order to correctly draw the fields. We don't return them in the sdk. "fields" are extracted using the parser app which is open source.

**Comment by DoubangoTelecom** [comment]
> "rotation" and "orientation" are returned to give feedback to the webapp in order to correctly draw the fields. We don't return them in the sdk. "fields" are extracted using the parser app which is open source.

Note that "orientation" is for Jpeg ExifOrientation from meta-data and the SDK don't have the information as we accept raw images as input. All our sample apps (Java, c++, c#, python ...) contains code showing how to extract the orientation info using the API https://www.doubango.org/SDKs/mrz/docs/cpp-api.html#_CPPv4N14ultimateMrzSdk15UltMrzSdkEngine15exifOrientationEPKvK6size_t

**Comment by LjSamardzic** [comment]
Thank you!
